//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MathserviceSoap")]
    public interface MathserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Average", ReplyAction="*")]
        double Average(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Average", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AverageAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sqrt", ReplyAction="*")]
        double Sqrt(double x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sqrt", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SqrtAsync(double x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MathserviceSoapChannel : Assignment5.ServiceReference1.MathserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathserviceSoapClient : System.ServiceModel.ClientBase<Assignment5.ServiceReference1.MathserviceSoap>, Assignment5.ServiceReference1.MathserviceSoap {
        
        public MathserviceSoapClient() {
        }
        
        public MathserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Average(double a, double b) {
            return base.Channel.Average(a, b);
        }
        
        public System.Threading.Tasks.Task<double> AverageAsync(double a, double b) {
            return base.Channel.AverageAsync(a, b);
        }
        
        public double Sqrt(double x) {
            return base.Channel.Sqrt(x);
        }
        
        public System.Threading.Tasks.Task<double> SqrtAsync(double x) {
            return base.Channel.SqrtAsync(x);
        }
    }
}
